import type { Readable } from 'node:stream';

/** Thrown by `Storage.open` when no object has that key. */
export class StorageNotFoundError extends Error {
  constructor(key: string) {
    super(`No stored object for key ${key}`);
    this.name = 'StorageNotFoundError';
  }
}

/**
 * Blob store for attachment files. Keys are generated by the API (never user input), shaped like
 * `workspaceId/taskId/attachmentId`. Local disk for now; an S3 implementation can follow.
 */
export interface Storage {
  /** Writes the stream under `key` (replacing any object there); resolves with the byte count. */
  put(key: string, body: Readable): Promise<{ size: number }>;
  /** Opens the object for reading. Throws `StorageNotFoundError` when it doesn't exist. */
  open(key: string): Promise<{ body: Readable; size: number }>;
  /** Removes the object; a missing object is not an error. */
  delete(key: string): Promise<void>;
}
